title: ESCAL MakerSpace Wiki
baseurl: "" # the subpath of your site, e.g. /blog

author:
  name: NuwanJ
  email: nuwanjaliyagoda@eng.pdn.ac.lk

description: > # this means to ignore newlines until "show_excerpts:"
  ""

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 # - jekyll-feed

# Google Analytics Tracking (optional)
ga_tracking: G-VX780EYHK1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

gh_edit_repository: "https://github.com/cepdnaclk/make.ce.pdn.ac.lk"
gh_edit_branch: "main"

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
    "graphic_templates",
    "*.py",
    "*.sh",
    "*.yml"
  ]


kramdown:
  syntax_highlighter_opts:
    block:
    line_numbers: false

# Guideline:https://www.digitalocean.com/community/tutorials/jekyll-compress-html0
compress_html:
  clippings: all
  comments: all
  endings: []
  startings: []
  blanklines: true
  profile: false
  # ignore:
  #   envs: all
